config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: 'pages#index'
	get '/secret', to: 'pages#secret', as: :secret
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :chats, :only => [:index, :create, :new, :show]
  get '/showchat/:user_id' => 'chats#showchat', action: :showchat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :sender, class_name: "User", primary_key: "id"
  belongs_to :receiver, class_name: "User", primary_key: "id"



	scope :between, -> (sender_id,receiver_id) do
 		where('(messages.sender_id = ? AND messages.receiver_id =?) OR (messages.sender_id = ? AND messages.receiver_id =?)', sender_id,receiver_id, receiver_id, sender_id)
 	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sent_messages, :class_name => "Message", :foreign_key => "sender_id"
  has_many :received_messages, :class_name => "Message", :foreign_key => "receiver_id"




  def self.user_type
  	['User','Trainer']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # devise_parameter_sanitizer.for(:sign_up) << :name
    # devise_parameter_sanitizer.for(:account_update) << :name
    # For Devise 4 and Rails 5 employ:
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :user_type])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :user_type])
	end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

	before_action :authenticate_user!
	
	def index
	end

	def showchat
		@receiver_id = params[:user_id]
		render :partial => 'showchat'
	end

	def create
		@message = Message.new(user_params)
		if @message.save
			redirect_to :back
		else
			flash[:alert] ="Something went wrong"
			redirect_to :back
		end
	end

	def edit
	end

	def show
	end

	def update
	end

	def destroy
	end


	private

	  def user_params
	    params.require(:message).permit(:message, :receiver_id).merge(sender_id: current_user.id)
	  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
	end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_showchat.html.erb
<div class="msg-wrap">
<% if Message.between(@receiver_id.to_i, current_user.id).present?%>
  <% Message.between(@receiver_id.to_i, current_user.id).all.reverse.each do |m|%>
      <div class="media msg">
          
        <div class="media-body">
            <small class="pull-right time"><i class="fa fa-clock-o"></i> <%= m.created_at.strftime("%d %b %H:%M")%></small>
            <h5 class="media-heading"><%= m.sender.name%></h5>

            <small class="col-lg-10"><%= m.message%></small>
        </div>
      </div>
  <% end %>
<% else %>
    <div class="media msg">
          
        <div class="media-body">
          <small class="col-lg-10">No Messages</small>
        </div>
      </div>
<% end %>
</div>

app/views/chats/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
              <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<div class="container">
    <div class="row">
      <div class="row">
          <div class="col-lg-6">
            <div class="btn-panel btn-panel-conversation">
                <button data-toggle="modal" data-target="#myModal" class="btn  col-lg-6 send-message-btn">
                  <i class="fa fa-plus"></i> New Message
                </button>
            </div>
          </div>
      </div>
    </div>
    <div class="row">

        


        <div class="message-wrap col-lg-8">
            <div class="msg-wrap">
            <% if Message.between(params[:id].to_i, current_user.id).present?%>
              <% Message.between(params[:id].to_i, current_user.id).first do |m|%>
                  <div class="media msg">
                      
                    <div class="media-body">
                        <small class="pull-right time"><i class="fa fa-clock-o"></i> 12:10am</small>
                        <h5 class="media-heading">Naimish Sakhpara</h5>

                        <small class="col-lg-10">Arnab Goswami: "Some people close to Congress Party and close to the government had a #secret #meeting in a farmhouse in Maharashtra in which Anna Hazare send some representatives and they had a meeting in the discussed how to go about this all fast and how eventually this will end."</small>
                    </div>
                  </div>
              <% end %>
            <% else %>
                <div class="media msg">
                      
                    <div class="media-body">
                      <small class="col-lg-10">No Messages</small>
                    </div>
                  </div>
            <% end %>
            </div>

            
           
        </div>

        <div class="conversation-wrap col-lg-3">

          <% User.all.each do |u|%>
            <a href="<%= chat_path(u.id)%>" class="<%= 'selected' if u.id==params[:id].to_i%>">
              <div class="media conversation">
                  
                  <div class="media-body">
                      <h4 class="media-heading"><%=u.name%></h4>
                      <% if u.user_type? %>  
                        <small><%=u.user_type%> <%='(You)' if current_user.id==u.id%></small>
                      <% else %>
                        <small>None<%='(You)' if current_user.id==u.id%></small>
                      <% end %>
                  </div>
              </div>
            </a>
          <% end %>
            
            
        </div>
    </div>
</div>
      
    </div>
  </div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">New Message</h4>
      </div>
      <div class="modal-body">

        <%= form_for(Message.new, url: chats_path) do |f| %>
          <div class="form-group">
            <%= f.label :receiver_id %>
            <%= f.select :receiver_id, User.all.collect {|u| [ "#{u.name} (#{u.name})", u.id ] }, { :include_blank => "Please select" } %>
          </div>


          <div class="form-group">
            <%= f.label :Message %>
            <%= f.text_field :message, class: 'form-control' %>
          </div>

          
          <div class="row">
            <div class="col-md-12">
              <%= f.submit "Send Message", class: 'btn btn-success pull-right' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

<% end %>

app/views/chats/show.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
              <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<div class="container">
    <div class="row">
      <div class="row">
          <div class="col-lg-6">
            <button data-toggle="modal" data-target="#myModal" class="btn btn-success col-lg-6 ">
              <i class="fa fa-plus"></i> New Message
            </button>
          </div>
      </div>
    </div>
    <div class="row">
        <div class="message-wrap col-lg-8"  id="divi">
            <div class="msg-wrap">
            <% if Message.between(params[:id].to_i, current_user.id).present?%>
              <% Message.between(params[:id].to_i, current_user.id).all.reverse.each do |m|%>
                  <div class="media msg">
                      
                    <div class="media-body">
                        <small class="pull-right time"><i class="fa fa-clock-o"></i> <%= m.created_at.strftime("%d %b %H:%M")%></small>
                        <h5 class="media-heading"><%= m.sender.name%></h5>

                        <small class="col-lg-10"><%= m.message%></small>
                    </div>
                  </div>
              <% end %>
            <% else %>
                <div class="media msg">
                      
                    <div class="media-body">
                      <small class="col-lg-10">No Contact Selected / No messages to show</small>
                    </div>
                  </div>
            <% end %>
            </div>
        </div>


        <div class="conversation-wrap col-lg-3">
          <% User.all.each do |u|%>
            <a href="<%= chat_path(u.id)%>" class="<%= 'selected' if u.id==params[:id].to_i%>">
              <div class="media conversation">
                  
                  <div class="media-body">
                      <h4 class="media-heading"><%=u.name%></h4>
                      <% if u.user_type? %>  
                        <small><%=u.user_type%> <%='(You)' if current_user.id==u.id%></small>
                      <% else %>
                        <small>None<%='(You)' if current_user.id==u.id%></small>
                      <% end %>
                  </div>
              </div>
            </a>
          <% end %>
        </div>
    </div>
</div>
      
    </div>
  </div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">New Message</h4>
      </div>
      <div class="modal-body">

        <%= form_for(Message.new, url: chats_path) do |f| %>
          <div class="form-group">
            <%= f.label :receiver_id %>
            <%= f.select :receiver_id, User.all.collect {|u| [ "#{u.name} (#{u.user_type})", u.id ] }, { :include_blank => "Please select" } %>
          </div>


          <div class="form-group">
            <%= f.label :Message %>
            <%= f.text_field :message, class: 'form-control' %>
          </div>

          
          <div class="row">
            <div class="col-md-12">
              <%= f.submit "Send Message", class: 'btn btn-success pull-right' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Sample Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Sample Application', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Dashboard', root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= "#{current_user.name} (You)"%>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'My Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Register', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

</div>

<%= yield :top_content %>

<div class="container">
  <h1><%= yield :header %></h1>

  <%= yield %>
</div>

<div id="footer">
  <div class="container">
    <p class="text-muted">Sample Application. Copyright 2018</a></p>
  </div>
</div>

</body>
</html>

app/views/pages/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome!</h1>
      <% if user_signed_in? %>
      	<p>
          <%= link_to 'Go to Messenger',  chats_path, class: 'btn btn-success btn-lg' %>
      	</p>
      <% else %>
	      <p>Register to get started.</p>
	      <p>
	        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-success btn-lg' %>
	      </p>
	  <% end %>
    </div>
  </div>
<% end %>